#!/usr/bin/env python3
"""Refresh _data/episodes.yml from the Architect Tomorrow YouTube playlist RSS feed.

Standard library only. YouTube's feed returns the 15 most recent items, so the
file keeps any older entries already present and merges new ones in.
Runs weekly in .github/workflows/update-episodes.yml, or locally:
    python3 scripts/update_episodes.py
"""
import os, re, sys, urllib.request
import xml.etree.ElementTree as ET

PLAYLIST = "PLu1Byoup02RbIKEeNSCAJcN4R7Uxb9paP"
FEED = f"https://www.youtube.com/feeds/videos.xml?playlist_id={PLAYLIST}"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "_data", "episodes.yml")
NS = {"a": "http://www.w3.org/2005/Atom", "yt": "http://www.youtube.com/xml/schemas/2015"}
HEADER = "# Generated by scripts/update_episodes.py (newest first). Safe to hand-edit titles.\n"


def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_existing():
    if not os.path.exists(OUT):
        return []
    items, cur = [], None
    for line in open(OUT, encoding="utf-8"):
        m = re.match(r'- id: "?([\w-]+)"?', line)
        if m:
            cur = {"id": m.group(1)}
            items.append(cur)
        m = re.match(r'  (title|date): "?(.*?)"?\s*$', line)
        if m and cur is not None:
            cur[m.group(1)] = m.group(2).replace('\\"', '"').replace("\\\\", "\\")
    return items


def main():
    req = urllib.request.Request(FEED, headers={"User-Agent": "Mozilla/5.0"})
    root = ET.fromstring(urllib.request.urlopen(req, timeout=30).read())
    fresh = [{"id": e.find("yt:videoId", NS).text, "title": e.find("a:title", NS).text.strip(),
              "date": e.find("a:published", NS).text[:10]} for e in root.findall("a:entry", NS)]
    seen = {e["id"] for e in fresh}
    merged = fresh + [e for e in load_existing() if e["id"] not in seen]
    merged.sort(key=lambda e: e.get("date", ""), reverse=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for e in merged:
            f.write(f'- id: {e["id"]}\n  title: {q(e["title"])}\n  date: {e["date"]}\n')
    print(f"wrote {len(merged)} episodes")


if __name__ == "__main__":
    sys.exit(main())
